### PR TITLE
Moving lib/igb and kmod/igb from openAVnu 

### PR DESCRIPTION
**Pull request by avinash-palleti**
Creating separate repo for lib/igb and kmod/igb as part of openAVnu restructuring.

### CODE REVIEW

**Comment by andrew-elder** [comment]
I'm going to accept this pull request later today unless anyone objects.

**Comment by avinash-palleti** [comment]
@andrew-elder Can you please enable this repo in Travis-CI before merging.
https://travis-ci.org/AVnu/igb_avb

**Comment by andrew-elder** [comment]
Should be activated now.

**Comment by avinash-palleti** [comment]
Thank you, i will just update this PR to trigger one run.

**Comment by avinash-palleti** [comment]
Done. Build is passing in travis.

**Comment by andrew-elder** [comment]
Nice!

**Comment by avinash-palleti** [comment]
@andrew-elder If there are no other comments, can you please merge this. I will update https://github.com/AVnu/OpenAvnu/pull/815 with latest commit hash

**Comment by andrew-elder** [comment]
Merging

**Pull request merged**
