### PR TITLE
merge from INTEL igb avb mainline driver

### PR DESCRIPTION
**Pull request by KnutSchrader**
tested on Fedora 32, kernel 5.8.10

### CODE REVIEW

**Comment by andrew-elder** [comment]
This change looks good to me. Anyone else?

**Comment by psow** [comment]
_supported_coalesce_params_ was added to the ethtool_ops in kernel 5.7 - this change won't work with older kernels. This line should have #ifdef ... #endif around it, with define based on kernel version (defined in kcompat.h, like in other, similar cases). Otherwise this change breaks backwards compatibility.

The igb_tx_map change is ok, but if we are introducing returning of a success/fail status in a function, it would also make sense to check this status in the place where this function is called.

**Comment by MarcinMiklas** [comment]
Kernel compatibility changes were already merged with another PR.

**Comment by KnutSchrader** [comment]
Hello, I have a question: Did you check the new driver with a talker application, e.g. simple talker?
Thanks a lot.

**Comment by MarcinMiklas** [comment]
I've checked with avtp pipeline, both talker and listener

**Pull request closed without merging**
