### PR TITLE
Fix compilation with kernel 5.4+

### PR DESCRIPTION
**Pull request by Heosuabi**
- Change make argument from SUBDIRS to M
 - Change struct to skb_frag_t -> bio_vec
 - Exclude num_online_cpus and pci-aspm if kernel > 5.4

Signed-off-by: Markus Eckert <meckert@blackned.de>

### CODE REVIEW

**Comment by andrew-elder** [comment]
Am I correct in assuming this commit breaks compatibility with older kernels?

**Comment by Heosuabi** [comment]
Sorry, my bad! You are correct.

I did some adjustments and added more checks against the Linux kernel version.
Tested the compilation with the following kernels:
4.9, 4.19 and 5.4

Edit:
Some additional information.
With Kernel 5.4 SUBDIRS was removed and only M is used as argument for make. But only passing M does work for a while now. Still... I'm not completely sure if this doesn't break something with very old kernels.

In addition, skb_frag_struct is completely removed and skb_frag_t is only another typedef for bio_vec.
page_offset was still available as a union to bv_offset, but was now removed.

**Comment by andrew-elder** [comment]
Thanks. Anyone using older kernels want to jump in and comment here?

**Comment by psow** [comment]
Most of this looks good to me. But few questions/doubts/suggestions:
1. num_online_cpus change seems to be not needed (it's defined in both older and newer kernels)
2. What triggered the "#include <linux/pci-aspm.h>" change?
3. This one is style related - we prefer to keep stuff like "#if ( LINUX_VERSION_CODE < KERNEL_VERSION(5,4,0) )" only in the kcompat.h. You can see a preferred way by looking for HAVE_NDO_SELECT_FALLBACK as an example.

**Comment by Heosuabi** [comment]
Hello. Thanks for taking a look.

Regarding your points:
1. smp_num_cpus does not exist anymore with newer kernel, that's why it fails to compile without version check.

2. pci-aspm.h is not available anymore.

3. Thank you. I'll take a look and change the code according to your preferred style.

Kind regards

**Comment by Heosuabi** [comment]
I updated the code to use the style similar to HAVE_NDO_SELECT_FALLBACK, using a new define for kernel lower than 5.4

Additional information to points 1 and 2, as mentioned earlier:
1. This problem is probably related to change: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0c09ab96fc820109d63097a2adcbbd20836b655f
Which removes the define for num_online_cpus. In this case it triggers the ifndef in kcompat.h, which results in a compile error because smp_num_cpus doesn't exist for a very long time (2014); see this change: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.4.42&id=46ffc934385860a127c04010f5f3ee225e06b87b

2. pci-aspm.h was merged with pci.h: See this change https://git.kernel.org/pub/scm/linux/kernel/git/helgaas/pci.git/commit/?id=7ce2e76a0420

**Review by psow — APPROVED** [review]
I see, they changed num_online_cpus from macro to function - that's why ifndef stopped seeing it. I missed that detail in my first look.

Ok, everything looks good to me. Thanks for adjusting the style and additional explanation.

**Comment by andrew-elder** [comment]
Thanks all, merging.

**Comment by andrew-elder** [comment]
Well, I don't have correct permissions to merge this. Someone else will have to do it!

**Comment by andrew-elder** [comment]
Can someone with merge priviledges please merge this PR.

**Comment by andrew-elder** [comment]
@AVnu-Administration - who has merge permissions on this repo?

**Comment by andrew-elder** [comment]
I have my permissions back! Merging...

**Pull request merged**
