### PR TITLE
Security enhancing GCC flags in the Makefile

### PR DESCRIPTION
**Pull request by psow**
Using those flags is recommended by our security team.

### CODE REVIEW

**Comment by psow** [comment]
I see that Travis CI build failed. This happened because it's current configuration uses GCC 4.8.4, while the "-fstack-protector-strong" flag was introduced in GCC 4.9 (and that version was released over 5 years ago).

**Comment by andrew-elder** [comment]
@psow - are you recommending we update Travis CI to use GCC 4.9? I think that would be ok. Any objections?

**Comment by psow** [comment]
@andrew-elder yes, updating Travis CI to GCC 4.9 is my recommendation

**Comment by andrew-elder** [comment]
Does anyone watching this have any objections?

**Comment by jfornal** [comment]
That change works for me. It's been consulted and as Piotr mentioned this is a new security related requirement at Intel.

**Comment by psow** [comment]
@andrew-elder I think we waited long enough. Could you do the Travis CI config update and do the merge? (if it passes after the config update of course)

**Comment by andrew-elder** [comment]
@psow - you should be able to apply changes to this file https://github.com/AVnu/igb_avb/blob/master/.travis.yml to this PR and that will update the compiler the Travis CI uses. Is that something you are able to do? Thanks for following up on this one!

**Comment by psow** [comment]
@andrew-elder Ok, I think it worked.

**Comment by andrew-elder** [comment]
Great, looks good. Thanks for taking those extra steps. Merging....

**Pull request merged**
