### PR TITLE
Some fixes for test and return codes

### PR DESCRIPTION
**Pull request by lalevee**
e1000_phy.c: add block for an if instruction
igb.c: return codes should be negative

### CODE REVIEW

**Comment by andrew-elder** [comment]
Does anyone have comments on this pull request? It has been open for quite a while..... !

**Comment by psow** [comment]
@andrew-elder Sorry for long delay, I missed this PR somehow.

I think the change in e1000_phy.c is ok.

Regarding the changes on the libigb (lib/igb.c) side, this is a user space code, so the convention of returning negative error values doesn't necessarily apply. It seems in the past the convention of positive error values in libigb was used. I agree that it's confusing that currently sometimes positive errors are returned and in other cases negative, however we also need to think about issues that changing this might introduce in other code that uses libigb.

I reported this issue to the people who are using the libigb from our side. They lean on the side of caution and think that we shouldn't change it for now.

@lalevee Did you check that in your case negative errors work ok in every situation for your whole software stack?

**Comment by lalevee** [comment]
All is OK on my side if you maintains the current code. I have my own 
repository, with revised code. I propose this merge essentially to have 
coherent code between the driver and the library.

I would like to take the opportunity to ask you if you know someone who 
has already implemented FQTSS with the AVNu driver, that I can contact 
to have some advices for doing that?
Thanks in advance
Philippe


Le 27/05/2019 à 12:42, Piotr Sowiński a écrit :

**Comment by andrew-elder** [comment]
@lalevee - It looks to me like the change to e1000_phy.c fixes a bug. Do you want to make a separate pull request with just that change in it? Thanks for doing/finding this BTW.

I'm included not to make all the error return changes at this time so as not to causes issues with current users. We can revisit this again if necessary.

I'm going to close this issue for now.

**Comment by psow** [comment]
@lalevee Please try the Intel customer support. I can't give you direct contact information.

**Pull request closed without merging**
